name: riverpod_for_serverpod_annotation
description: Annotations for generating Riverpod providers from Serverpod endpoints.
version: 3.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  meta: any
  # path: ^1.8.0

dev_dependencies:
  lints:
  test:
