name: riverpod_for_serverpod_runtime
description: Runtime cache primitives used by generated Riverpod providers for Serverpod endpoints.
version: 3.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: any
  riverpod: ">=2.0.0 <4.0.0"

dev_dependencies:
  lints:
  test:
